# Dockerfile.dev для Strapi бэкенда
FROM node:20-alpine

# Установка рабочей директории
WORKDIR /app

# Копирование package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование исходного кода
COPY . .

# Открытие порта
EXPOSE 1337

# Команда запуска в режиме разработки
CMD ["npm", "run", "dev"]
