/**
 * Admin app configuration for Hi-Catering Orders Management
 */

export default {
    config: {
        // Replace the favicon
        head: {
            favicon: '/favicon.ico',
        },
        // Add a custom logo
        auth: {
            logo: '/logo.png',
        },
        // Override or extend the theme
        theme: {
            light: {
                colors: {
                    primary100: '#f6ecfc',
                    primary200: '#e0c1f4',
                    primary500: '#ac73e6',
                    primary600: '#9736e8',
                    primary700: '#8312d1',
                    danger700: '#b72b1a',
                    success600: '#328048',
                    warning600: '#d02b20',
                },
            },
        },
        // Extend the translations
        translations: {
            en: {
                'app.components.LeftMenu.navbrand.title': 'Hi-Catering Admin',
                'app.components.LeftMenu.navbrand.workplace': 'Orders Management',
                'content-manager.containers.ListPage.displayedFields': 'Displayed Fields',
                'content-manager.containers.Edit.pluginHeader.title.new': 'Create new entry',
                'content-manager.containers.Edit.pluginHeader.title.edit': 'Edit entry',
                'content-manager.containers.Edit.pluginHeader.title.duplicate': 'Duplicate entry',
                'content-manager.containers.Edit.pluginHeader.title.delete': 'Delete entry',
                'content-manager.containers.Edit.pluginHeader.title.deleteAll': 'Delete all entries',
                'content-manager.containers.Edit.pluginHeader.title.publish': 'Publish',
                'content-manager.containers.Edit.pluginHeader.title.unpublish': 'Unpublish',
                'content-manager.containers.Edit.pluginHeader.title.save': 'Save',
                'content-manager.containers.Edit.pluginHeader.title.saveAndPublish': 'Save and publish',
                'content-manager.containers.Edit.pluginHeader.title.saveAndUnpublish': 'Save and unpublish',
                'content-manager.containers.Edit.pluginHeader.title.saveAndContinue': 'Save and continue',
                'content-manager.containers.Edit.pluginHeader.title.saveAndDuplicate': 'Save and duplicate',
                'content-manager.containers.Edit.pluginHeader.title.saveAndNew': 'Save and create new',
                'content-manager.containers.Edit.pluginHeader.title.saveAndClose': 'Save and close',
                'content-manager.containers.Edit.pluginHeader.title.saveAndView': 'Save and view',
                'content-manager.containers.Edit.pluginHeader.title.saveAndEdit': 'Save and edit',
                'content-manager.containers.Edit.pluginHeader.title.saveAndList': 'Save and go to list',
                'content-manager.containers.Edit.pluginHeader.title.saveAndSearch': 'Save and search',
                'content-manager.containers.Edit.pluginHeader.title.saveAndFilter': 'Save and filter',
                'content-manager.containers.Edit.pluginHeader.title.saveAndSort': 'Save and sort',
                'content-manager.containers.Edit.pluginHeader.title.saveAndGroup': 'Save and group',
                'content-manager.containers.Edit.pluginHeader.title.saveAndExport': 'Save and export',
                'content-manager.containers.Edit.pluginHeader.title.saveAndImport': 'Save and import',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBackup': 'Save and backup',
                'content-manager.containers.Edit.pluginHeader.title.saveAndRestore': 'Save and restore',
                'content-manager.containers.Edit.pluginHeader.title.saveAndArchive': 'Save and archive',
                'content-manager.containers.Edit.pluginHeader.title.saveAndUnarchive': 'Save and unarchive',
                'content-manager.containers.Edit.pluginHeader.title.saveAndMove': 'Save and move',
                'content-manager.containers.Edit.pluginHeader.title.saveAndCopy': 'Save and copy',
                'content-manager.containers.Edit.pluginHeader.title.saveAndMoveToTrash': 'Save and move to trash',
                'content-manager.containers.Edit.pluginHeader.title.saveAndRestoreFromTrash': 'Save and restore from trash',
                'content-manager.containers.Edit.pluginHeader.title.saveAndEmptyTrash': 'Save and empty trash',
                'content-manager.containers.Edit.pluginHeader.title.saveAndPermanentlyDelete': 'Save and permanently delete',
                'content-manager.containers.Edit.pluginHeader.title.saveAndSoftDelete': 'Save and soft delete',
                'content-manager.containers.Edit.pluginHeader.title.saveAndHardDelete': 'Save and hard delete',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkDelete': 'Save and bulk delete',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkEdit': 'Save and bulk edit',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkPublish': 'Save and bulk publish',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkUnpublish': 'Save and bulk unpublish',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkDuplicate': 'Save and bulk duplicate',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkMove': 'Save and bulk move',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkCopy': 'Save and bulk copy',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkExport': 'Save and bulk export',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkImport': 'Save and bulk import',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkBackup': 'Save and bulk backup',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkRestore': 'Save and bulk restore',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkArchive': 'Save and bulk archive',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkUnarchive': 'Save and bulk unarchive',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkMoveToTrash': 'Save and bulk move to trash',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkRestoreFromTrash': 'Save and bulk restore from trash',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkEmptyTrash': 'Save and bulk empty trash',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkPermanentlyDelete': 'Save and bulk permanently delete',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkSoftDelete': 'Save and bulk soft delete',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkHardDelete': 'Save and bulk hard delete',
                // Dish type field and enum values
                'content-manager.components.FieldSelect.label.api::dish.dish.type': 'Type',
                'content-type-builder.popUpForm.enum.values.dish.type.cold': 'Cold',
                'content-type-builder.popUpForm.enum.values.dish.type.hot': 'Hot',
                'content-type-builder.popUpForm.enum.values.dish.type.side': 'Side Dish',
                'content-type-builder.popUpForm.enum.values.dish.type.baked': 'Baked Goods',
                'content-type-builder.popUpForm.enum.values.dish.type.drink': 'Drink',
                'content-type-builder.popUpForm.enum.values.dish.type.sweet': 'Sweet/Dessert',
                'content-type-builder.popUpForm.enum.values.dish.type.other': 'Other',
            },
            ru: {
                'app.components.LeftMenu.navbrand.title': 'Hi-Catering Админ',
                'app.components.LeftMenu.navbrand.workplace': 'Управление заказами',
                'content-manager.containers.ListPage.displayedFields': 'Отображаемые поля',
                'content-manager.containers.Edit.pluginHeader.title.new': 'Создать новую запись',
                'content-manager.containers.Edit.pluginHeader.title.edit': 'Редактировать запись',
                'content-manager.containers.Edit.pluginHeader.title.duplicate': 'Дублировать запись',
                'content-manager.containers.Edit.pluginHeader.title.delete': 'Удалить запись',
                'content-manager.containers.Edit.pluginHeader.title.deleteAll': 'Удалить все записи',
                'content-manager.containers.Edit.pluginHeader.title.publish': 'Опубликовать',
                'content-manager.containers.Edit.pluginHeader.title.unpublish': 'Снять с публикации',
                'content-manager.containers.Edit.pluginHeader.title.save': 'Сохранить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndPublish': 'Сохранить и опубликовать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndUnpublish': 'Сохранить и снять с публикации',
                'content-manager.containers.Edit.pluginHeader.title.saveAndContinue': 'Сохранить и продолжить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndDuplicate': 'Сохранить и дублировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndNew': 'Сохранить и создать новую',
                'content-manager.containers.Edit.pluginHeader.title.saveAndClose': 'Сохранить и закрыть',
                'content-manager.containers.Edit.pluginHeader.title.saveAndView': 'Сохранить и просмотреть',
                'content-manager.containers.Edit.pluginHeader.title.saveAndEdit': 'Сохранить и редактировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndList': 'Сохранить и перейти к списку',
                'content-manager.containers.Edit.pluginHeader.title.saveAndSearch': 'Сохранить и найти',
                'content-manager.containers.Edit.pluginHeader.title.saveAndFilter': 'Сохранить и фильтровать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndSort': 'Сохранить и сортировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndGroup': 'Сохранить и группировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndExport': 'Сохранить и экспортировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndImport': 'Сохранить и импортировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBackup': 'Сохранить и создать резервную копию',
                'content-manager.containers.Edit.pluginHeader.title.saveAndRestore': 'Сохранить и восстановить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndArchive': 'Сохранить и архивировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndUnarchive': 'Сохранить и разархивировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndMove': 'Сохранить и переместить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndCopy': 'Сохранить и скопировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndMoveToTrash': 'Сохранить и переместить в корзину',
                'content-manager.containers.Edit.pluginHeader.title.saveAndRestoreFromTrash': 'Сохранить и восстановить из корзины',
                'content-manager.containers.Edit.pluginHeader.title.saveAndEmptyTrash': 'Сохранить и очистить корзину',
                'content-manager.containers.Edit.pluginHeader.title.saveAndPermanentlyDelete': 'Сохранить и удалить навсегда',
                'content-manager.containers.Edit.pluginHeader.title.saveAndSoftDelete': 'Сохранить и мягко удалить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndHardDelete': 'Сохранить и жестко удалить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkDelete': 'Сохранить и массово удалить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkEdit': 'Сохранить и массово редактировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkPublish': 'Сохранить и массово опубликовать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkUnpublish': 'Сохранить и массово снять с публикации',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkDuplicate': 'Сохранить и массово дублировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkMove': 'Сохранить и массово переместить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkCopy': 'Сохранить и массово скопировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkExport': 'Сохранить и массово экспортировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkImport': 'Сохранить и массово импортировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkBackup': 'Сохранить и массово создать резервную копию',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkRestore': 'Сохранить и массово восстановить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkArchive': 'Сохранить и массово архивировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkUnarchive': 'Сохранить и массово разархивировать',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkMoveToTrash': 'Сохранить и массово переместить в корзину',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkRestoreFromTrash': 'Сохранить и массово восстановить из корзины',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkEmptyTrash': 'Сохранить и массово очистить корзину',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkPermanentlyDelete': 'Сохранить и массово удалить навсегда',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkSoftDelete': 'Сохранить и массово мягко удалить',
                'content-manager.containers.Edit.pluginHeader.title.saveAndBulkHardDelete': 'Сохранить и массово жестко удалить',
                // Dish type field and enum values - Russian translations
                'content-manager.components.FieldSelect.label.api::dish.dish.type': 'Тип блюда',
                'content-type-builder.popUpForm.enum.values.dish.type.cold': 'Холодное',
                'content-type-builder.popUpForm.enum.values.dish.type.hot': 'Горячее',
                'content-type-builder.popUpForm.enum.values.dish.type.side': 'Гарнир',
                'content-type-builder.popUpForm.enum.values.dish.type.baked': 'Выпечка',
                'content-type-builder.popUpForm.enum.values.dish.type.drink': 'Напиток',
                'content-type-builder.popUpForm.enum.values.dish.type.sweet': 'Сладкое',
                'content-type-builder.popUpForm.enum.values.dish.type.other': 'Другое',
            },
        },
        // Disable video tutorials
        tutorials: false,
        // Disable notifications about new Strapi releases
        notifications: { releases: false },
    },
    bootstrap() {
        console.log('Hi-Catering Orders Management Admin Panel loaded');
    },
};